env:
  browser: true
  es6: true
  webextensions: true
  jest: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  browser: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {}

